/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SecureDataInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addAdmin"
      | "admins"
      | "checkDataIntegrity"
      | "emergencyStop"
      | "finalizeDecryption"
      | "finalizePublicDecryption"
      | "finalizeResults"
      | "getContactInfo"
      | "getDecryptedContactInfo"
      | "getEncryptedHandles"
      | "getVersion"
      | "hasContactInfo"
      | "isAdmin"
      | "isContactInfoComplete"
      | "owner"
      | "protocolId"
      | "removeAdmin"
      | "submitContactInfo"
      | "submitContactInfoSimple"
      | "updateContactField"
      | "updateContactFieldSimple"
      | "validateContactInfo"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AdminAdded"
      | "AdminRemoved"
      | "ContactDataRetrieved"
      | "ContactDataSubmitted"
      | "ContactInfoDecrypted"
      | "ContactInfoSubmitted"
      | "ContactInfoUpdated"
      | "DataIntegrityChecked"
      | "DecryptionFinalized"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "admins", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "checkDataIntegrity",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyStop",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeDecryption",
    values: [
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizePublicDecryption",
    values: [
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeResults",
    values: [
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getContactInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDecryptedContactInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedHandles",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVersion",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasContactInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isContactInfoComplete",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "removeAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitContactInfo",
    values: [
      BigNumberish,
      BytesLike,
      BigNumberish,
      BytesLike,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "submitContactInfoSimple",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateContactField",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateContactFieldSimple",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "validateContactInfo",
    values: [BigNumberish, string, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "addAdmin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "admins", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "checkDataIntegrity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyStop",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeDecryption",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizePublicDecryption",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeResults",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContactInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDecryptedContactInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedHandles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getVersion", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasContactInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isAdmin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isContactInfoComplete",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitContactInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitContactInfoSimple",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateContactField",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateContactFieldSimple",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateContactInfo",
    data: BytesLike
  ): Result;
}

export namespace AdminAddedEvent {
  export type InputTuple = [
    admin: AddressLike,
    addedBy: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [admin: string, addedBy: string, timestamp: bigint];
  export interface OutputObject {
    admin: string;
    addedBy: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AdminRemovedEvent {
  export type InputTuple = [
    admin: AddressLike,
    removedBy: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    admin: string,
    removedBy: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    admin: string;
    removedBy: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContactDataRetrievedEvent {
  export type InputTuple = [
    user: AddressLike,
    retriever: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    retriever: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    retriever: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContactDataSubmittedEvent {
  export type InputTuple = [user: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [user: string, timestamp: bigint];
  export interface OutputObject {
    user: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContactInfoDecryptedEvent {
  export type InputTuple = [
    user: AddressLike,
    phoneNumber: BigNumberish,
    emailHash: BigNumberish,
    emergencyContact: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    phoneNumber: bigint,
    emailHash: bigint,
    emergencyContact: bigint
  ];
  export interface OutputObject {
    user: string;
    phoneNumber: bigint;
    emailHash: bigint;
    emergencyContact: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContactInfoSubmittedEvent {
  export type InputTuple = [user: AddressLike];
  export type OutputTuple = [user: string];
  export interface OutputObject {
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContactInfoUpdatedEvent {
  export type InputTuple = [user: AddressLike, fieldType: BigNumberish];
  export type OutputTuple = [user: string, fieldType: bigint];
  export interface OutputObject {
    user: string;
    fieldType: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DataIntegrityCheckedEvent {
  export type InputTuple = [
    user: AddressLike,
    isValid: boolean,
    integrityScore: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    isValid: boolean,
    integrityScore: bigint
  ];
  export interface OutputObject {
    user: string;
    isValid: boolean;
    integrityScore: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DecryptionFinalizedEvent {
  export type InputTuple = [user: AddressLike, name: string, email: string];
  export type OutputTuple = [user: string, name: string, email: string];
  export interface OutputObject {
    user: string;
    name: string;
    email: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [
    previousOwner: AddressLike,
    newOwner: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    previousOwner: string,
    newOwner: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SecureData extends BaseContract {
  connect(runner?: ContractRunner | null): SecureData;
  waitForDeployment(): Promise<this>;

  interface: SecureDataInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addAdmin: TypedContractMethod<[admin: AddressLike], [void], "nonpayable">;

  admins: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  checkDataIntegrity: TypedContractMethod<
    [user: AddressLike],
    [[boolean, bigint] & { isValid: boolean; integrityScore: bigint }],
    "nonpayable"
  >;

  emergencyStop: TypedContractMethod<[pause: boolean], [void], "nonpayable">;

  finalizeDecryption: TypedContractMethod<
    [
      user: AddressLike,
      phoneNumber: BigNumberish,
      emailHash: BigNumberish,
      emergencyContact: BigNumberish,
      name: string,
      email: string
    ],
    [void],
    "nonpayable"
  >;

  finalizePublicDecryption: TypedContractMethod<
    [
      user: AddressLike,
      phoneNumber: BigNumberish,
      emailHash: BigNumberish,
      emergencyContact: BigNumberish,
      name: string,
      email: string
    ],
    [void],
    "nonpayable"
  >;

  finalizeResults: TypedContractMethod<
    [
      user: AddressLike,
      phoneNumber: BigNumberish,
      emailHash: BigNumberish,
      emergencyContact: BigNumberish,
      name: string,
      email: string
    ],
    [void],
    "nonpayable"
  >;

  getContactInfo: TypedContractMethod<
    [user: AddressLike],
    [
      [string, string, string] & {
        phoneNumber: string;
        emailHash: string;
        emergencyContact: string;
      }
    ],
    "view"
  >;

  getDecryptedContactInfo: TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, bigint, bigint, string, string, boolean] & {
        phoneNumber: bigint;
        emailHash: bigint;
        emergencyContact: bigint;
        name: string;
        email: string;
        decrypted: boolean;
      }
    ],
    "view"
  >;

  getEncryptedHandles: TypedContractMethod<
    [user: AddressLike],
    [[bigint, bigint, bigint]],
    "view"
  >;

  getVersion: TypedContractMethod<[], [string], "view">;

  hasContactInfo: TypedContractMethod<[user: AddressLike], [boolean], "view">;

  isAdmin: TypedContractMethod<[account: AddressLike], [boolean], "view">;

  isContactInfoComplete: TypedContractMethod<
    [user: AddressLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  removeAdmin: TypedContractMethod<[admin: AddressLike], [void], "nonpayable">;

  submitContactInfo: TypedContractMethod<
    [
      phoneHandle: BigNumberish,
      phoneInputProof: BytesLike,
      emailHandle: BigNumberish,
      emailInputProof: BytesLike,
      emergencyHandle: BigNumberish,
      emergencyInputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  submitContactInfoSimple: TypedContractMethod<
    [
      encryptedPhone: BytesLike,
      encryptedEmail: BytesLike,
      encryptedEmergency: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  updateContactField: TypedContractMethod<
    [fieldType: BigNumberish, handle: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  updateContactFieldSimple: TypedContractMethod<
    [fieldType: BigNumberish, encryptedValue: BytesLike],
    [void],
    "nonpayable"
  >;

  validateContactInfo: TypedContractMethod<
    [phone: BigNumberish, email: string, emergency: BigNumberish],
    [[boolean, bigint] & { isValid: boolean; errorCode: bigint }],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addAdmin"
  ): TypedContractMethod<[admin: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "admins"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "checkDataIntegrity"
  ): TypedContractMethod<
    [user: AddressLike],
    [[boolean, bigint] & { isValid: boolean; integrityScore: bigint }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "emergencyStop"
  ): TypedContractMethod<[pause: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "finalizeDecryption"
  ): TypedContractMethod<
    [
      user: AddressLike,
      phoneNumber: BigNumberish,
      emailHash: BigNumberish,
      emergencyContact: BigNumberish,
      name: string,
      email: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "finalizePublicDecryption"
  ): TypedContractMethod<
    [
      user: AddressLike,
      phoneNumber: BigNumberish,
      emailHash: BigNumberish,
      emergencyContact: BigNumberish,
      name: string,
      email: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "finalizeResults"
  ): TypedContractMethod<
    [
      user: AddressLike,
      phoneNumber: BigNumberish,
      emailHash: BigNumberish,
      emergencyContact: BigNumberish,
      name: string,
      email: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getContactInfo"
  ): TypedContractMethod<
    [user: AddressLike],
    [
      [string, string, string] & {
        phoneNumber: string;
        emailHash: string;
        emergencyContact: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDecryptedContactInfo"
  ): TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, bigint, bigint, string, string, boolean] & {
        phoneNumber: bigint;
        emailHash: bigint;
        emergencyContact: bigint;
        name: string;
        email: string;
        decrypted: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEncryptedHandles"
  ): TypedContractMethod<
    [user: AddressLike],
    [[bigint, bigint, bigint]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVersion"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "hasContactInfo"
  ): TypedContractMethod<[user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isAdmin"
  ): TypedContractMethod<[account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isContactInfoComplete"
  ): TypedContractMethod<[user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "removeAdmin"
  ): TypedContractMethod<[admin: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitContactInfo"
  ): TypedContractMethod<
    [
      phoneHandle: BigNumberish,
      phoneInputProof: BytesLike,
      emailHandle: BigNumberish,
      emailInputProof: BytesLike,
      emergencyHandle: BigNumberish,
      emergencyInputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitContactInfoSimple"
  ): TypedContractMethod<
    [
      encryptedPhone: BytesLike,
      encryptedEmail: BytesLike,
      encryptedEmergency: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateContactField"
  ): TypedContractMethod<
    [fieldType: BigNumberish, handle: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateContactFieldSimple"
  ): TypedContractMethod<
    [fieldType: BigNumberish, encryptedValue: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "validateContactInfo"
  ): TypedContractMethod<
    [phone: BigNumberish, email: string, emergency: BigNumberish],
    [[boolean, bigint] & { isValid: boolean; errorCode: bigint }],
    "view"
  >;

  getEvent(
    key: "AdminAdded"
  ): TypedContractEvent<
    AdminAddedEvent.InputTuple,
    AdminAddedEvent.OutputTuple,
    AdminAddedEvent.OutputObject
  >;
  getEvent(
    key: "AdminRemoved"
  ): TypedContractEvent<
    AdminRemovedEvent.InputTuple,
    AdminRemovedEvent.OutputTuple,
    AdminRemovedEvent.OutputObject
  >;
  getEvent(
    key: "ContactDataRetrieved"
  ): TypedContractEvent<
    ContactDataRetrievedEvent.InputTuple,
    ContactDataRetrievedEvent.OutputTuple,
    ContactDataRetrievedEvent.OutputObject
  >;
  getEvent(
    key: "ContactDataSubmitted"
  ): TypedContractEvent<
    ContactDataSubmittedEvent.InputTuple,
    ContactDataSubmittedEvent.OutputTuple,
    ContactDataSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "ContactInfoDecrypted"
  ): TypedContractEvent<
    ContactInfoDecryptedEvent.InputTuple,
    ContactInfoDecryptedEvent.OutputTuple,
    ContactInfoDecryptedEvent.OutputObject
  >;
  getEvent(
    key: "ContactInfoSubmitted"
  ): TypedContractEvent<
    ContactInfoSubmittedEvent.InputTuple,
    ContactInfoSubmittedEvent.OutputTuple,
    ContactInfoSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "ContactInfoUpdated"
  ): TypedContractEvent<
    ContactInfoUpdatedEvent.InputTuple,
    ContactInfoUpdatedEvent.OutputTuple,
    ContactInfoUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "DataIntegrityChecked"
  ): TypedContractEvent<
    DataIntegrityCheckedEvent.InputTuple,
    DataIntegrityCheckedEvent.OutputTuple,
    DataIntegrityCheckedEvent.OutputObject
  >;
  getEvent(
    key: "DecryptionFinalized"
  ): TypedContractEvent<
    DecryptionFinalizedEvent.InputTuple,
    DecryptionFinalizedEvent.OutputTuple,
    DecryptionFinalizedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "AdminAdded(address,address,uint256)": TypedContractEvent<
      AdminAddedEvent.InputTuple,
      AdminAddedEvent.OutputTuple,
      AdminAddedEvent.OutputObject
    >;
    AdminAdded: TypedContractEvent<
      AdminAddedEvent.InputTuple,
      AdminAddedEvent.OutputTuple,
      AdminAddedEvent.OutputObject
    >;

    "AdminRemoved(address,address,uint256)": TypedContractEvent<
      AdminRemovedEvent.InputTuple,
      AdminRemovedEvent.OutputTuple,
      AdminRemovedEvent.OutputObject
    >;
    AdminRemoved: TypedContractEvent<
      AdminRemovedEvent.InputTuple,
      AdminRemovedEvent.OutputTuple,
      AdminRemovedEvent.OutputObject
    >;

    "ContactDataRetrieved(address,address,uint256)": TypedContractEvent<
      ContactDataRetrievedEvent.InputTuple,
      ContactDataRetrievedEvent.OutputTuple,
      ContactDataRetrievedEvent.OutputObject
    >;
    ContactDataRetrieved: TypedContractEvent<
      ContactDataRetrievedEvent.InputTuple,
      ContactDataRetrievedEvent.OutputTuple,
      ContactDataRetrievedEvent.OutputObject
    >;

    "ContactDataSubmitted(address,uint256)": TypedContractEvent<
      ContactDataSubmittedEvent.InputTuple,
      ContactDataSubmittedEvent.OutputTuple,
      ContactDataSubmittedEvent.OutputObject
    >;
    ContactDataSubmitted: TypedContractEvent<
      ContactDataSubmittedEvent.InputTuple,
      ContactDataSubmittedEvent.OutputTuple,
      ContactDataSubmittedEvent.OutputObject
    >;

    "ContactInfoDecrypted(address,uint8,uint8,uint8)": TypedContractEvent<
      ContactInfoDecryptedEvent.InputTuple,
      ContactInfoDecryptedEvent.OutputTuple,
      ContactInfoDecryptedEvent.OutputObject
    >;
    ContactInfoDecrypted: TypedContractEvent<
      ContactInfoDecryptedEvent.InputTuple,
      ContactInfoDecryptedEvent.OutputTuple,
      ContactInfoDecryptedEvent.OutputObject
    >;

    "ContactInfoSubmitted(address)": TypedContractEvent<
      ContactInfoSubmittedEvent.InputTuple,
      ContactInfoSubmittedEvent.OutputTuple,
      ContactInfoSubmittedEvent.OutputObject
    >;
    ContactInfoSubmitted: TypedContractEvent<
      ContactInfoSubmittedEvent.InputTuple,
      ContactInfoSubmittedEvent.OutputTuple,
      ContactInfoSubmittedEvent.OutputObject
    >;

    "ContactInfoUpdated(address,uint8)": TypedContractEvent<
      ContactInfoUpdatedEvent.InputTuple,
      ContactInfoUpdatedEvent.OutputTuple,
      ContactInfoUpdatedEvent.OutputObject
    >;
    ContactInfoUpdated: TypedContractEvent<
      ContactInfoUpdatedEvent.InputTuple,
      ContactInfoUpdatedEvent.OutputTuple,
      ContactInfoUpdatedEvent.OutputObject
    >;

    "DataIntegrityChecked(address,bool,uint8)": TypedContractEvent<
      DataIntegrityCheckedEvent.InputTuple,
      DataIntegrityCheckedEvent.OutputTuple,
      DataIntegrityCheckedEvent.OutputObject
    >;
    DataIntegrityChecked: TypedContractEvent<
      DataIntegrityCheckedEvent.InputTuple,
      DataIntegrityCheckedEvent.OutputTuple,
      DataIntegrityCheckedEvent.OutputObject
    >;

    "DecryptionFinalized(address,string,string)": TypedContractEvent<
      DecryptionFinalizedEvent.InputTuple,
      DecryptionFinalizedEvent.OutputTuple,
      DecryptionFinalizedEvent.OutputObject
    >;
    DecryptionFinalized: TypedContractEvent<
      DecryptionFinalizedEvent.InputTuple,
      DecryptionFinalizedEvent.OutputTuple,
      DecryptionFinalizedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address,uint256)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
